### PR TITLE
Handle opts.cwd correctly when using lintText

### PR DESCRIPTION
**Pull request by lucasmarshall**

### CODE REVIEW

**Comment by lucasmarshall** [comment]
@jcorbin @Matt-Esch @malandrew @Raynos

**Comment by andrewdeandrade** [comment]
@lucasmarshall please look at how feross/standard solves this issue (I believe they had this bug too and resolved it) and either cherry-pick that commit or manually apply those changes and submit as a new PR.

https://github.com/feross/standard/blob/master/index.js

**Comment by lucasmarshall** [comment]
@malandrew Looks like feross/standard doesn't have this particular issue fixed, actually. I just tested the latest from their master and it definitely doesn't work as expected.

**Comment by andrewdeandrade** [comment]
Can you give me more details on the issue this is fixing and how to reproduce it?

**Pull request closed without merging**
