### PR TITLE
Ban the try catch rule.

### PR DESCRIPTION
**Pull request by Raynos**
This is a subset of the custom-rules branch.

r: @jcorbin @Matt-Esch @malandrew

### CODE REVIEW

**Comment by Raynos** [comment]
The whole point of standard is to not have a bunch of configuration files in the project.

i.e. no .jshint no .eslint no .editorconfig

If you really want the file I can put it back but it seems against the spirit of the standard project.

**Comment by andrewdeandrade** [comment]
It serves a different purpose than the linter. The linter highlights things. The editorconfig on filesave actually cleans up all trailing characters and inserts a newline. I wish the linter could do that.

Once the esformatter stuff is solid and can fix that stuff automatically, we should be able to remove editorconfig (insofar as JS files are concerned, but it also cleans up markdown files and other file types).

**Comment by Raynos** [comment]
people should just configure their editors once and comply with the linter. 

the editor config file is just noise.

But if you want to keep it i'll revert that commit.

**Comment by Raynos** [comment]
Updated; added editor config back.

**Comment by andrewdeandrade** [comment]
LGTM

**Pull request merged**
