### PR TITLE
Added --babel option, restrict no-extra-parens to functions only

### PR DESCRIPTION
**Pull request by rtsao**
The ES6 config extends the base config, and the Babel config extends the ES6 config.

Addresses:
- https://github.com/uber/standard/issues/31
- https://github.com/uber/standard/issues/35

### CODE REVIEW

**Comment by rtsao** [comment]
@malandrew @Raynos

**Comment by andrewdeandrade** [comment]
I'd like to see #31 addressed in es6 mode.

I'd like to see more discussion about the merit of supporting experimental features other than, this is something I want to use. I'm not a fan of paving that cowpath. If people really want those features on a case by case basis, uber-standard supports an eslintrc file in your project.

On top of not wanting to pave a cowpath, I also think that splintering things down into a third standard is the wrong way. We now have two standards, this will put us at three. https://xkcd.com/927/

**Comment by rtsao** [comment]
For the purposes of this diff, ES6 inherits all the standard rules, so #31 is addressed in all modes.

Also I don't view it as different standards. Babel mode doesn't introduce any new linting rules or even change existing ones, it merely allows for parsing of files that use language features included in Babel. Furthermore, when we transition to node 4.0, ES6 mode will presumably become the new default and we will be back to two.

I just think linting and transpilation should have feature parity. If people are using Babel, they ought to still  be able to use uber-standard. Is it better for people to roll their own linting configuration? I'd rather pave the Babel cowpath then have people using no standard lint config at all.

**Comment by chrisirhc** [comment]
I agree with the reasoning here. If we pick Babel for experimental features, the changes in this PR would standardize the choice for linting experimental features (babel-eslint) as well as where they should come from (babel).

Update: Removed comment about custom parsers. Looks like that was a cache issue, works fine.

**Pull request merged**
