### PR TITLE
Add ES6 linking support

### PR DESCRIPTION
**Pull request by freeqaz**
Manually move over the config from eslint environments so that we have full control.

### CODE REVIEW

**Comment by Raynos** [comment]
This is a better start; it gives us good visibility.

**Comment by Raynos** [comment]
There are two discussions here; 
- For an ES6 code base, which rules are good and bad. I think that discussion can be punted
- How do we use a linter for ES5 and ES6 code bases.

## How do we use a linter for ES5 and ES6 code bases.

We currently use `uber-standard` for node0.10 applications and lean heavily on it for correctness and style consistency. It might seem harmless to turn these features off but it would allow people to write ES6 features without the linter telling them it's invalid ES5.
- We could say; turn es6 on. if you write ES6 for node0.10 your tests will fail.
- We could say; es6 should be a flag;
- We could say; es6 is an opt-in for per project .eslintrc files
- We could say; es6 is out of scope for uber-standard
- We could feature detect for es6 by relying on es6 modules and having file specific linting

**Comment by Raynos** [comment]
Another option is to say "ES6 is simply a different language" this means we would have a seperate linter with seperate rules.

The reasoning behind that is we might want to turn some ES5 features off; for example always use classes, never use constructor functions.

**Comment by lxe** [comment]
> We could say; es6 should be a flag;

Make it a flag and be :+1:

**Comment by freeqaz** [comment]
Superseded by https://github.com/uber/standard/pull/13

**Pull request closed without merging**
